r"""Goal of this script is to make an animation of similar data plotted by zxtm_wake_steers.py

The output animation should be easy to use in powerpoint (.pptx format) and markdown (.md format)

The animation should show data for turbines T1, T3 and T7 and as much data from the ZXTM LiDAR (mounted on T7) as possible.

The animations should show a birds eye view of the three turbines and data from the LiDAR where it is measured (various ranges in front of T7).

The ZXTM scans in a cone in front of the turbine with a 15 degree half angle (30 degree full angle).

The turbine cartesian coordinates are available in scripts/wake_steering_analysis/floris_config/hot_emgauss.yaml (coordinate arrays are for the 21 turbines T1 to T21).

The turbines should be visualized with a small circle (3m diameter) exactly at their coordinate which never moves (represents the tower). A rectangle represents the nacelle; the rectagle is 10m long and 4m wide and is attached to the tower slightly off centre; if the turbine is pointing west then there is 6m of rectangle to the left of the centre of the tower and 4m to the right. The rotos is a line 82m long attached to the long end of the nacelle; if the turbine is facing west the rotor line is vertical and centre is 6m left of the tower centre.

The turbines yawpos_col (see zxtm_wake_steers.py) gives the orientation of the nacelle relative to true north. For example if this is 270 then the turbine is pointing west; the rectangle's longer side is horizontal and the rotor is on the left side of the rectangle. If the yawpos_col is 0 then the turbine is pointing north; the rectangle's longer side is vertical and the rotor is on the top side of the rectangle.
The turbines name should be shown above it.
The turbines smoothed power (see zxtm_wake_steers.py) should be shown as a colour of the rectangle (for example from blue for 0% power to red for 100% power) and a small text annotation to 0dep.

For the ZXTM the columns 'Left LOS Speed (m/s) at Rotor Segment Height 59.0m' and 'Right LOS Speed (m/s) at Rotor Segment Height 59.0m' are used. The 'Range (m)' column gives the distance of the wind speed measurement in front of T7 in metres (10, 48, 64, 85, 126 and 208). A series should be computed which is the smoothed wind speed for each of left and right and for each range. This results in 2 * 6 = 12 wind speed measurements in front of T7. These 12 measurements should be visualised as colours (blue for low wind speed, red for high wind speed) located in the correct positions in front of T7. Note these points will move as T7 yaws.

The ZXTM also has columns 'Left LOS Speed (m/s) at Rotor Segment Height 26.2m', 'Left LOS Speed (m/s) at Rotor Segment Height 42.6m', 'Left LOS Speed (m/s) at Rotor Segment Height 75.4m', 'Left LOS Speed (m/s) at Rotor Segment Height 91.8m' and the same columns for Right. Along with the 59.0m measurement this gives wind speed at 5 heights above ground level. These should be visualised for each range starting from 85m. This is the "vertical profile" plot

The data to be plotted is 2026-02-20 00:00 to 07:00

The same yaw position, wind direction and steering on/off timeline plotted in zxtm_wake_steers.py lines 84 to 110 should be plotted to with a vertical line showing what timestamp the animation is at. The vertical line advances from left to right as the animation runs.
An example image already generated by zxtm_wake_steers.py is at C:\Users\aclerc\temp\hill-of-towie-open-source-analysis\output\zxtm_wake_steers\T03-T07-T01\T03 steering for T07 2026-02-20 0120 to 0500.png

The output is an animation file showing:
- a descriptive title at the top
- the timeline plot as the first 'row' spanning all columns
- below the timeline plot three axes:
-- The "Right" vertical profile plot. This is shown on the left of the figure because the wind is coming from SSW in this time period, so the "Right" measurements appear on the left from a birds eye view perspective.
-- The main animation with turbines and wind speeds in their cartesian cooredinates
-- The "Left" vertical profile plot

The speed of the animation should be adjustable but as a starting point aim for the animation to last 60s.
"""

import logging
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.animation import PillowWriter
from matplotlib.colors import Normalize
from matplotlib.lines import Line2D
from tqdm import tqdm

from hot_open.fastlog_helpers import load_hot_fl_data
from hot_open.lidar_helpers import load_zx_lidar_fl_data
from hot_open.settings import get_filestore_dir, get_out_dir
from scripts.logger import setup_logger
from scripts.wake_steering_analysis.inspect_data import (
    LOCAL_TEMPORARY_DIR,
    NORTH_CORRECTIONS,
    WTG_FL_ACT_POWER_COL,
    WTG_FL_YAW_POS_COL,
    ZXTM_WD_COL,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Tunable constants
# ---------------------------------------------------------------------------
PLOT_START = pd.Timestamp("2026-02-20 00:00", tz="UTC")
PLOT_END = pd.Timestamp("2026-02-20 07:00", tz="UTC")
FRAME_INTERVAL_S = 10        # seconds of real data per animation frame
ANIMATION_DURATION_S = 60    # target GIF duration in seconds
SMOOTHING_WINDOW = 600       # rolling-mean window in seconds

# Load from this earlier start so the rolling mean is fully populated at PLOT_START
LOAD_START = PLOT_START - pd.Timedelta(seconds=SMOOTHING_WINDOW)

# ---------------------------------------------------------------------------
# Fixed geometry (metres)
# ---------------------------------------------------------------------------
ROTOR_DIAMETER_M = 82.0
NACELLE_FRONT_M = 6.0        # nacelle extends this far forward of tower centre
NACELLE_REAR_M = 4.0         # nacelle extends this far behind tower centre
NACELLE_HALF_WIDTH_M = 2.0   # half the nacelle width
HALF_ANGLE_DEG = 15.0        # ZXTM cone half-angle

# ---------------------------------------------------------------------------
# ZXTM column definitions
# ---------------------------------------------------------------------------
PROFILE_HEIGHTS_M: list[float] = [26.2, 42.6, 59.0, 75.4, 91.8]
PROFILE_RANGES_M: list[float] = [85.0, 126.0, 208.0]   # used in vertical profiles
ZXTM_ALL_RANGES_M: list[float] = [10.0, 48.0, 64.0, 85.0, 126.0, 208.0]

WS_COLS: list[str] = [
    f"{side} LOS Speed (m/s) at Rotor Segment Height {h}m"
    for side in ("Left", "Right")
    for h in PROFILE_HEIGHTS_M
]
WS_59M_COLS: list[str] = [
    "Left LOS Speed (m/s) at Rotor Segment Height 59.0m",
    "Right LOS Speed (m/s) at Rotor Segment Height 59.0m",
]

# ---------------------------------------------------------------------------
# Turbine config
# ---------------------------------------------------------------------------
WTG_NUMBERS = [1, 3, 7]
REF_NAME = "T01"
STEERING_NAME = "T03"
DEP_NAME = "T07"
TOGGLE_COL = "computed_driver_post_processed_toggle_state"
YAW_POS_COL = "computed_driver_pre_processed_yaw_direction_true_degrees"
WD_COL = "computed_core_post_processed_consensus_wind_direction_true_degrees"

# Coordinates from floris_config/hot_emgauss.yaml (0-indexed: T01=0, T03=2, T07=6)
TURBINE_COORDS: dict[str, tuple[float, float]] = {
    "T01": (134.13, 328.33),
    "T03": (0.0, 646.29),
    "T07": (187.61, 987.50),
}


# ---------------------------------------------------------------------------
# Task 2: Load and preprocess data
# ---------------------------------------------------------------------------


def _add_smoothed(
    df: pd.DataFrame, *, col: str, new_col: str, min_periods: int = SMOOTHING_WINDOW // 2
) -> None:
    df[new_col] = df[col].rolling(window=SMOOTHING_WINDOW, min_periods=min_periods).mean()


def _load_wtg_data() -> dict[str, pd.DataFrame]:
    """Load fastlog for T01/T03/T07, apply north corrections, add smoothed power column."""
    wtg_fl_df = load_hot_fl_data(
        data_dir=get_filestore_dir(),
        wtg_numbers=WTG_NUMBERS,
        start_dt=LOAD_START,
        end_dt_excl=PLOT_END,
        extra_tags=[TOGGLE_COL, YAW_POS_COL, WD_COL],
    )
    for wtg, correction in NORTH_CORRECTIONS.items():
        if wtg in wtg_fl_df.columns.get_level_values(0):
            wtg_fl_df[(wtg, WTG_FL_YAW_POS_COL)] = (
                wtg_fl_df[(wtg, WTG_FL_YAW_POS_COL)] + correction
            ) % 360

    result: dict[str, pd.DataFrame] = {}
    for name in (REF_NAME, STEERING_NAME, DEP_NAME):
        df = wtg_fl_df[name].copy()
        _add_smoothed(df, col=WTG_FL_ACT_POWER_COL, new_col="smoothed_pw")
        # Clip to animation window after smoothing so warm-up rows are excluded
        result[name] = df.loc[PLOT_START:PLOT_END]
    return result


# ---------------------------------------------------------------------------
# Task 3: Load and smooth ZXTM LiDAR data
# ---------------------------------------------------------------------------


def _load_zxtm_data() -> dict[float, pd.DataFrame]:
    """Load ZXTM lidar fastlog, smooth each range independently.

    Returns {range_m: smoothed_df} where each df has WS_COLS smoothed with a
    600 s rolling mean (min_periods = SMOOTHING_WINDOW // 5).
    """
    zxtm_fl_df = load_zx_lidar_fl_data(
        data_dir=LOCAL_TEMPORARY_DIR / "lidar_data",
        lidar_unit_id="5060",
        start_dt=LOAD_START,
        end_dt_excl=PLOT_END,
        remove_bad_values=True,
    )
    zxtm_fl_df[ZXTM_WD_COL] = (zxtm_fl_df[ZXTM_WD_COL] + NORTH_CORRECTIONS["ZXTM"]) % 360

    result: dict[float, pd.DataFrame] = {}
    for range_val, group in zxtm_fl_df.groupby("Range (m)"):
        available = [col for col in WS_COLS if col in group.columns]
        smoothed = group[available].rolling(
            window=SMOOTHING_WINDOW, min_periods=SMOOTHING_WINDOW // 5
        ).mean()
        # Clip to animation window after smoothing so warm-up rows are excluded
        result[float(range_val)] = smoothed.loc[PLOT_START:PLOT_END]
    return result


# ---------------------------------------------------------------------------
# Task 4: Compute color bounds for normalization
# ---------------------------------------------------------------------------


def _compute_color_bounds(
    wtg_data: dict[str, pd.DataFrame],
    zxtm_smoothed: dict[float, pd.DataFrame],
) -> tuple[float, float, float, float]:
    """Return (pw_vmin, pw_vmax, ws_vmin, ws_vmax) from the full data window."""
    all_pw = pd.concat([df["smoothed_pw"].dropna() for df in wtg_data.values()])
    pw_vmin = float(all_pw.min())
    pw_vmax = float(all_pw.max())

    ws_series: list[pd.Series] = []
    for df in zxtm_smoothed.values():
        for col in WS_COLS:
            if col in df.columns:
                ws_series.append(df[col].dropna())
    all_ws = pd.concat(ws_series)
    ws_vmin = float(all_ws.min())
    ws_vmax = float(all_ws.max())

    return pw_vmin, pw_vmax, ws_vmin, ws_vmax


# ---------------------------------------------------------------------------
# Task 5: Draw turbines
# ---------------------------------------------------------------------------


def _local_to_world(
    tx: float, ty: float, yaw_rad: float, dx: float, dy: float
) -> tuple[float, float]:
    """Convert local (x_right, y_forward) offset to world (east, north) position."""
    cos_y = np.cos(yaw_rad)
    sin_y = np.sin(yaw_rad)
    return tx + dx * cos_y + dy * sin_y, ty - dx * sin_y + dy * cos_y


def _draw_turbine(
    ax: plt.Axes,
    *,
    tx: float,
    ty: float,
    yaw_deg: float,
    power: float,
    name: str,
    pw_norm: Normalize,
    pw_cmap,
) -> None:
    yaw_rad = np.deg2rad(yaw_deg)

    # Tower (static 3 m diameter circle)
    ax.add_patch(
        mpatches.Circle((tx, ty), radius=1.5, facecolor="gray", edgecolor="black", zorder=4)
    )

    # Nacelle polygon: 6 m forward, 4 m behind, ±2 m wide
    corners_local = [
        (-NACELLE_HALF_WIDTH_M, -NACELLE_REAR_M),
        (NACELLE_HALF_WIDTH_M, -NACELLE_REAR_M),
        (NACELLE_HALF_WIDTH_M, NACELLE_FRONT_M),
        (-NACELLE_HALF_WIDTH_M, NACELLE_FRONT_M),
    ]
    corners_world = [_local_to_world(tx, ty, yaw_rad, dx, dy) for dx, dy in corners_local]
    color = pw_cmap(pw_norm(power))
    ax.add_patch(
        mpatches.Polygon(
            corners_world, closed=True, facecolor=color, edgecolor="black", zorder=3
        )
    )

    # Rotor line (82 m, centred at nacelle front)
    half_r = ROTOR_DIAMETER_M / 2
    r_left = _local_to_world(tx, ty, yaw_rad, -half_r, NACELLE_FRONT_M)
    r_right = _local_to_world(tx, ty, yaw_rad, half_r, NACELLE_FRONT_M)
    ax.plot([r_left[0], r_right[0]], [r_left[1], r_right[1]], "k-", linewidth=2.5, zorder=5)

    # Turbine name (offset upward in screen space regardless of yaw)
    ax.text(tx, ty + 55, name, ha="center", va="bottom", fontsize=8, zorder=6)

    # Power annotation to the right of the nacelle
    ann_pos = _local_to_world(tx, ty, yaw_rad, NACELLE_HALF_WIDTH_M + 5, 0.0)
    ax.text(ann_pos[0], ann_pos[1], f"{power:.0f} kW", ha="left", va="center", fontsize=7, zorder=6)


# ---------------------------------------------------------------------------
# Task 6: Draw ZXTM LiDAR points
# ---------------------------------------------------------------------------


def _draw_zxtm_points(
    ax: plt.Axes,
    *,
    t07_x: float,
    t07_y: float,
    t07_yaw_deg: float,
    zxtm_smoothed: dict[float, pd.DataFrame],
    ts: pd.Timestamp,
    ws_norm: Normalize,
    ws_cmap,
) -> None:
    yaw_rad = np.deg2rad(t07_yaw_deg)
    half_angle_rad = np.deg2rad(HALF_ANGLE_DEG)
    # Range (m) is the horizontal forward distance to the scan plane.
    # The beam's slant distance in plan view is Range / cos(half_angle).
    dist_factor = 1.0 / np.cos(half_angle_rad)

    xs: list[float] = []
    ys: list[float] = []
    colors: list = []
    sizes: list[float] = []

    for range_val in ZXTM_ALL_RANGES_M:
        if range_val not in zxtm_smoothed:
            continue
        df = zxtm_smoothed[range_val]
        idx = df.index.get_indexer([ts], method="nearest")[0]
        if idx < 0:
            continue
        row = df.iloc[idx]

        dist = range_val * dist_factor
        right_angle = yaw_rad + half_angle_rad
        left_angle = yaw_rad - half_angle_rad

        for ws, angle in [
            (row.get("Right LOS Speed (m/s) at Rotor Segment Height 59.0m", np.nan), right_angle),
            (row.get("Left LOS Speed (m/s) at Rotor Segment Height 59.0m", np.nan), left_angle),
        ]:
            xs.append(t07_x + dist * np.sin(angle))
            ys.append(t07_y + dist * np.cos(angle))
            norm_ws = float(ws_norm(ws)) if not pd.isna(ws) else 0.5
            colors.append(ws_cmap(norm_ws))
            sizes.append(30.0 + norm_ws * 170.0)

    if xs:
        ax.scatter(xs, ys, c=colors, s=sizes, zorder=6, edgecolors="k", linewidths=0.4)


# ---------------------------------------------------------------------------
# Task 7: Draw vertical wind speed profiles
# ---------------------------------------------------------------------------


_RANGE_COLORS = [plt.cm.Greens(v) for v in (0.40, 0.65, 0.90)]  # 85, 126, 208 m


def _draw_vertical_profiles(
    ax_right: plt.Axes,
    ax_left: plt.Axes,
    *,
    ts: pd.Timestamp,
    zxtm_smoothed: dict[float, pd.DataFrame],
    ws_xlim: tuple[float, float],
) -> None:
    for ax, side, title in [
        (ax_right, "Right", "Right LOS"),
        (ax_left, "Left", "Left LOS"),
    ]:
        ax.cla()
        ax.set_xlim(ws_xlim)
        ax.set_ylim(min(PROFILE_HEIGHTS_M) - 5, max(PROFILE_HEIGHTS_M) + 5)
        ax.set_xlabel("wind speed (m/s)", fontsize=8)
        ax.set_ylabel("height AGL (m)", fontsize=8)
        ax.set_title(title, fontsize=9)
        ax.grid(True, alpha=0.4)

        for range_val, color in zip(PROFILE_RANGES_M, _RANGE_COLORS):
            if range_val not in zxtm_smoothed:
                continue
            df = zxtm_smoothed[range_val]
            idx = df.index.get_indexer([ts], method="nearest")[0]
            if idx < 0:
                continue
            row = df.iloc[idx]
            ws_vals = [
                row.get(f"{side} LOS Speed (m/s) at Rotor Segment Height {h}m", np.nan)
                for h in PROFILE_HEIGHTS_M
            ]
            ax.plot(
                ws_vals,
                PROFILE_HEIGHTS_M,
                color=color,
                marker="o",
                markersize=4,
                linewidth=1.5,
                label=f"{range_val:.0f} m",
            )
        ax.legend(loc="lower right", fontsize=7)


# ---------------------------------------------------------------------------
# Task 8: Initialize figure and shade toggle regions
# ---------------------------------------------------------------------------


def _shade_toggle(ax: plt.Axes, *, steer_df: pd.DataFrame, toggle_col: str) -> None:
    ylow, yhigh = ax.get_ylim()
    ax.fill_between(
        steer_df.index, ylow, yhigh,
        where=steer_df[toggle_col] == 0, color="red", alpha=0.05, label="steering off",
    )
    ax.fill_between(
        steer_df.index, ylow, yhigh,
        where=steer_df[toggle_col] == 1, color="green", alpha=0.05, label="steering on",
    )
    ax.set_ylim(ylow, yhigh)


def _init_figure(
    wtg_data: dict[str, pd.DataFrame],
    pw_vmin: float,
    pw_vmax: float,
    ws_vmin: float,
    ws_vmax: float,
) -> tuple[plt.Figure, plt.Axes, plt.Axes, plt.Axes, plt.Axes, Line2D]:
    """Build figure, draw timeline once. Returns (fig, ax_tl, ax_be, ax_rp, ax_lp, vline)."""
    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(
        2, 3,
        width_ratios=[1, 2, 1],
        height_ratios=[1, 2],
        hspace=0.40,
        wspace=0.35,
    )
    ax_tl = fig.add_subplot(gs[0, :])   # timeline — spans all columns
    ax_rp = fig.add_subplot(gs[1, 0])   # Right vertical profile (left column)
    ax_be = fig.add_subplot(gs[1, 1])   # birds-eye view (centre, wider)
    ax_lp = fig.add_subplot(gs[1, 2])   # Left vertical profile (right column)

    fig.suptitle(
        "Hill of Towie — T03 wake steering for T07 — 2026-02-20",
        fontsize=11,
    )

    # --- Timeline (drawn once) ---
    ref_df = wtg_data[REF_NAME]
    steer_df = wtg_data[STEERING_NAME]
    dep_df = wtg_data[DEP_NAME]

    ax_tl.plot(ref_df.index, ref_df[WD_COL], color="C0", linestyle=":", alpha=0.5,
               label=f"{REF_NAME} wind dir")
    ax_tl.plot(ref_df.index, ref_df[YAW_POS_COL], color="C0",
               label=f"{REF_NAME} yaw pos")
    ax_tl.plot(steer_df.index, steer_df[WD_COL], color="C1", linestyle=":", alpha=0.5,
               label=f"{STEERING_NAME} wind dir")
    ax_tl.plot(steer_df.index, steer_df[YAW_POS_COL], color="C1",
               label=f"{STEERING_NAME} yaw pos")
    ax_tl.plot(dep_df.index, dep_df[WD_COL], color="C2", linestyle=":", alpha=0.5,
               label=f"{DEP_NAME} wind dir")
    ax_tl.plot(dep_df.index, dep_df[YAW_POS_COL], color="C2",
               label=f"{DEP_NAME} yaw pos")
    _shade_toggle(ax_tl, steer_df=steer_df, toggle_col=TOGGLE_COL)
    ax_tl.set_ylabel("direction [degN]")
    ax_tl.legend(bbox_to_anchor=(1.01, 1), loc="upper left", fontsize=7, frameon=True)
    ax_tl.grid(True, alpha=0.4)
    plt.setp(ax_tl.xaxis.get_majorticklabels(), rotation=45, ha="right")

    # Vertical time cursor — x-position updated each frame
    vline = ax_tl.axvline(PLOT_START, color="black", linewidth=1.5, linestyle="--", zorder=5)

    # --- Colorbars (drawn once, stable across frames) ---
    pw_sm = plt.cm.ScalarMappable(norm=Normalize(pw_vmin, pw_vmax), cmap="plasma")
    pw_sm.set_array([])
    fig.colorbar(pw_sm, ax=ax_be, location="right", label="power (kW)", shrink=0.5, pad=0.02)

    ws_sm = plt.cm.ScalarMappable(norm=Normalize(ws_vmin, ws_vmax), cmap="RdBu_r")
    ws_sm.set_array([])
    fig.colorbar(ws_sm, ax=ax_be, location="bottom", label="wind speed (m/s)", shrink=0.5, pad=0.06)

    return fig, ax_tl, ax_be, ax_rp, ax_lp, vline


# ---------------------------------------------------------------------------
# Task 9: Animation loop and __main__ block
# ---------------------------------------------------------------------------


def _run_animation(
    *,
    wtg_data: dict[str, pd.DataFrame],
    zxtm_smoothed: dict[float, pd.DataFrame],
    pw_vmin: float,
    pw_vmax: float,
    ws_vmin: float,
    ws_vmax: float,
    out_dir: Path,
    smoke_test:bool=False,
) -> None:
    fig, ax_tl, ax_be, ax_rp, ax_lp, vline = _init_figure(
        wtg_data, pw_vmin, pw_vmax, ws_vmin, ws_vmax
    )

    pw_norm = Normalize(pw_vmin, pw_vmax)
    pw_cmap = plt.cm.plasma
    ws_norm = Normalize(ws_vmin, ws_vmax)
    ws_cmap = plt.cm.RdBu_r
    ws_xlim = (ws_vmin - 0.2, ws_vmax + 0.2)

    all_x = [c[0] for c in TURBINE_COORDS.values()]
    all_y = [c[1] for c in TURBINE_COORDS.values()]
    be_xlim = (min(all_x) - 300, max(all_x) + 300)
    be_ylim = (min(all_y) - 300, max(all_y) + 300)

    ref_df = wtg_data[REF_NAME]
    steer_df = wtg_data[STEERING_NAME]
    dep_df = wtg_data[DEP_NAME]
    t07_x, t07_y = TURBINE_COORDS[DEP_NAME]
    name_to_df = {REF_NAME: ref_df, STEERING_NAME: steer_df, DEP_NAME: dep_df}

    timestamps = ref_df.resample(f"{FRAME_INTERVAL_S}s").first().index
    fps = len(timestamps) / ANIMATION_DURATION_S

    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / "zxtm_wake_steer_animation.gif"
    logger.info("rendering %d frames at %.1f fps -> %s", len(timestamps), fps, output_path)

    writer = PillowWriter(fps=fps)
    if smoke_test:
        timestamps=timestamps[250:300]
    with writer.saving(fig, str(output_path), dpi=100):
        for i, ts in enumerate(tqdm(timestamps, desc="frames")):
            # --- Birds-eye ---
            ax_be.cla()
            ax_be.set_xlim(be_xlim)
            ax_be.set_ylim(be_ylim)
            ax_be.set_aspect("equal")
            ax_be.set_xlabel("easting (m)", fontsize=8)
            ax_be.set_ylabel("northing (m)", fontsize=8)
            ax_be.set_title(ts.strftime("%H:%M:%S UTC"), fontsize=9)
            ax_be.grid(True, alpha=0.3)

            t07_yaw = 0.0
            for name, (tx, ty) in TURBINE_COORDS.items():
                df = name_to_df[name]
                idx = df.index.get_indexer([ts], method="nearest")[0]
                row = df.iloc[idx]
                raw_yaw = row[YAW_POS_COL]
                yaw = float(raw_yaw) if not pd.isna(raw_yaw) else 0.0
                power = float(row["smoothed_pw"]) if not pd.isna(row["smoothed_pw"]) else 0.0
                _draw_turbine(
                    ax_be,
                    tx=tx, ty=ty, yaw_deg=yaw, power=power,
                    name=name, pw_norm=pw_norm, pw_cmap=pw_cmap,
                )
                if name == DEP_NAME:
                    t07_yaw = yaw
            _draw_zxtm_points(
                ax_be,
                t07_x=t07_x, t07_y=t07_y, t07_yaw_deg=t07_yaw,
                zxtm_smoothed=zxtm_smoothed, ts=ts,
                ws_norm=ws_norm, ws_cmap=ws_cmap,
            )

            # --- Vertical profiles ---
            _draw_vertical_profiles(
                ax_rp, ax_lp, ts=ts, zxtm_smoothed=zxtm_smoothed, ws_xlim=ws_xlim
            )

            # --- Timeline cursor ---
            vline.set_xdata([ts, ts])

            fig.canvas.draw()
            writer.grab_frame()

            if i % 200 == 0:
                logger.info("frame %d / %d", i, len(timestamps))

    logger.info("saved %s", output_path)
    plt.close(fig)


if __name__ == "__main__":
    smoke_test=True
    out_dir = get_out_dir(dir_name=Path(__file__).stem)
    log_path = out_dir / f"{Path(__file__).stem}.log"
    setup_logger(log_path)
    logger.info("log file is at %s", log_path)

    logger.info("loading WTG fastlog data...")
    wtg_data = _load_wtg_data()

    logger.info("loading ZXTM lidar data...")
    zxtm_smoothed = _load_zxtm_data()

    logger.info("computing colour bounds...")
    pw_vmin, pw_vmax, ws_vmin, ws_vmax = _compute_color_bounds(wtg_data, zxtm_smoothed)
    logger.info(
        "power %.0f–%.0f kW  |  wind speed %.1f–%.1f m/s",
        pw_vmin, pw_vmax, ws_vmin, ws_vmax,
    )

    _run_animation(
        wtg_data=wtg_data,
        zxtm_smoothed=zxtm_smoothed,
        pw_vmin=pw_vmin,
        pw_vmax=pw_vmax,
        ws_vmin=ws_vmin,
        ws_vmax=ws_vmax,
        out_dir=out_dir,
        smoke_test=smoke_test,
    )